services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: vigilia-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

  postgres:
    image: postgres:17
    container_name: vigilia-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vigilia
      POSTGRES_PASSWORD: vigilia
      POSTGRES_DB: vigilia
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  grafana-data:
  postgres-data: