"""add alert idempotency constraint

Revision ID: d98d8d2e647b
Revises: 8c50ce1c1d3b
Create Date: 2026-06-30 19:56:25.350290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98d8d2e647b'
down_revision: Union[str, Sequence[str], None] = '8c50ce1c1d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_alert_source_fingerprint_starts_at_status",
        "alerts",
        ["source", "fingerprint", "starts_at", "status"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_alert_source_fingerprint_starts_at_status",
        "alerts",
        type_="unique",
    )
    # ### end Alembic commands ###
